trend_scan:
  description: >-
    Analyze public interest signals and propose 5 promising subtopics per topic in {{ topics | join(', ') }}
    with a one-sentence rationale each, noting recency or evergreen appeal. Output a single consolidated
    list (max 300 words). Avoid speculation; rely on observable signals.
  expected_output: >-
    Markdown section titled "Proposed Angles" with 5–15 bullet points across all topics, each with a
    short rationale.
  agent: trendhunter
  output_file: outputs/{{ (topic | default(topics[0])) | lower | replace(' ', '_') }}/trends.md

web_research:
  description: >-
    First, decide if {{ topic | default(topics[0]) }} implies a list (e.g., ‘top/best/recommended’) or tips. 
    If list: gather 6–10 contenders with title, author, year, 1-line rationale, and 1–2 solid sources each. 
    If tips: Find recent, *practical tips* for {{ topics | join(', ') }}.
    EXCLUDE virtual/360/VR tours, commercials, trailers, or vendor promos. Prefer sources within 12 months.
    If a result looks like a tour or promo, discard it and search again with -("virtual tour" OR 360 OR VR) filters..
  expected_output: >-
    "Sources" section with 4–8 links; each has title, publisher, date (YYYY-MM-DD), and a 1-line summary.
  agent: researcher
  output_file: outputs/{{ (topic | default(topics[0])) | lower | replace(' ', '_') }}/research.md

outline:
  description: >-
    From the Sources, pick ONE clear angle.
    Output Hook + 3–5 Beats + Close. No tours/promos. Keep total under 35s.
  expected_output: >-
    ## Outline
    Hook:
    Beats:
    - …
    Close:
  agent: writer
  output_file: outputs/{{ (topic | default(topics[0])) | lower | replace(' ', '_') }}/outline.md

script:
  description: >-
    Turn the Outline into a 120–160 word script for {{ channels | join(', ') }}.
    If intent = list, structure as: 
    - Hook 
    - Items #5 - #1 (3–5s each, title on screen) 
    - Close. Keep to 35–45s total.
    If intent = tips 
    Use this structure strictly:
    - Hook (1 sentence)
    - Tip 1–5 (imperative voice, ~15–20 words each), map [1],[2]… to Sources
    - Close (1 sentence)
    Do not introduce tours or vendors. Only claim what the Sources support.
  agent: writer
  output_file: outputs/{{ (topic | default(topics[0])) | lower | replace(' ', '_') }}/script.md

edit_pass:
  description: >-
    Tighten the script for clarity and pacing, fix hedging, unify tone, and ensure all bracketed references map
    to existing sources. Keep within 160 words.
  expected_output: >-
    Polished script under "Script (final)" in Markdown.
  agent: editor
  output_file: outputs/{{ (topic | default(topics[0])) | lower | replace(' ', '_') }}/script.md