trend_scan:
  description: >-
    Analyze public interest signals and propose 5 promising subtopics per topic in {{ topics | join(', ') }}
    with a one-sentence rationale each, noting recency or evergreen appeal. Output a single consolidated
    list (max 300 words). Avoid speculation; rely on observable signals.
  expected_output: >-
    Markdown section titled "Proposed Angles" with 5–15 bullet points across all topics, each with a
    short rationale.
  agent: trendhunter
  output_file: outputs/{{ topic | lower | replace(' ', '_') }}/{{ run_id }}/trends.md

web_research:
  description: >-
    You MUST use the tools. First, call the Serper search tool with `search_query` built from:
      "{{ topic | default(topics[0]) }} (tips OR guide OR how to OR best OR top)"
      Exclude obvious junk: -("virtual tour" OR 360 OR VR OR promo) -site:pinterest.com -site:x.com
      Then, for each candidate link (max 2 per domain), call the ScrapeWebsite tool to fetch the page
      and extract: page_title, site_name (domain), and publication_date from meta tags
      (article:published_time, og:updated_time, or visible date). If scraping fails, skip that link.
      DO NOT invent URLs or dates. If Serper returns nothing usable, output "NO_SOURCES_FOUND".

      Finally, output ONLY a fenced JSON block with this schema:
      {
        "topic": "{{ topic | default(topics[0]) }}",
        "sources": [
          {"title":"...", "url":"...", "site":"...", "date":"YYYY-MM-DD or null", "summary":"..."}
        ]
      }
  expected_output: >-
    A single fenced JSON block (no prose) matching the schema above, 4–8 sources total, max 2 per domain.
  agent: researcher
  output_file: outputs/{{ topic | lower | replace(' ', '_') }}/{{ run_id }}/research.md

outline:
  description: >-
    From the Sources, pick ONE clear angle.
    Output Hook + 3–5 Beats + Close. No tours/promos. Keep total under 35s.
  expected_output: >-
    ## Outline
    Hook:
    Beats:
    - …
    Close:
  agent: writer
  output_file: outputs/{{ topic | lower | replace(' ', '_') }}/{{ run_id }}/outline.md

script:
  description: >-
    Turn the Outline into a 120–160 word script for {{ channels | join(', ') }}.
    If intent = list, structure as: 
    - Hook 
    - Items #5 - #1 (3–5s each, title on screen) 
    - Close. Keep to 35–45s total.
    If intent = tips 
    Use this structure strictly:
    - Hook (1 sentence)
    - Tip 1–5 (imperative voice, ~15–20 words each), map [1],[2]… to Sources
    - Close (1 sentence)
    Do not introduce tours or vendors. Only claim what the Sources support.
  agent: writer
  output_file: outputs/{{ topic | lower | replace(' ', '_') }}/{{ run_id }}/script.md

edit_pass:
  description: >-
    Tighten the script for clarity and pacing, fix hedging, unify tone, and ensure all bracketed references map
    to existing sources. Keep within 160 words.
  expected_output: >-
    Polished script under "Script (final)" in Markdown.
  agent: editor
  output_file: outputs/{{ topic | lower | replace(' ', '_') }}/{{ run_id }}/script.md